name: GH Pages Deploy

on:
  push:
    branches: [main]
    paths-ignore:
      - READMME.md

  pull_request:
    branches: [main]
    paths-ignore:
      - README.md

jobs:
  build-deploy:
    name: Build and deploy

    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Set up Ruby 💎
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.3
          bundler-cache: true

      - name: Build 🏗
        run: bundle exec jekyll build --trace

      - name: Deploy to GH Pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
          cname: cc4d.tech
          exclude_assets: '.github,markdown-tutorial.md,markdown-tutorial.html,README.md,LICENCE,docker-compose.yml,package.json,package-lock.json'